version: "3.9"
services:
  crossplatform:
    container_name: cross
    build:
      context: .
      dockerfile: devops.Dockerfile
    networks:
      - proxy-network
    environment:
      - BASE_URL
    restart: always
    
networks:
  proxy-network:
    external: true
